server:
 port: 2727

spring:
 application:
  name: Attendance

 datasource:
  url: jdbc:mysql://localhost:3306/Attendance?createDatabaseIfNotExist=true
  username: root
  password: uplo@123

 jpa:
  hibernate:
   ddl-auto: update